#! /bin/sh
# ~/.config/bspwm/bspwmrc

# Article followed for hybrid setup w/ XFCE: https://github.com/bgdawes/bspwm-xfce-dotfiles/wiki


. "${HOME}/.config/bspwm/autostart.sh"

num_monitors="$(xrandr --query | grep ' connected' | wc -l)"
if [ $num_monitors -eq 1 ]; then
  for d in VIII VII VI X; do
    bspc desktop -r $d 2>&1 /dev/null || true
  done
  bspc monitor -d I II III IV V VI VII VIII IX X
else
  bspc monitor DP-1-3-3 -d I II III IV V
  bspc monitor DP-1-3-1 -d VI VII VIII IX
fi

bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

bspc config border_width 0
bspc config window_gap 30
bspc config top_padding 25
bspc config left_padding 0
bspc config right_padding 0
bspc config bottom_padding -10

bspc config split_ratio 0.55b
bspc config borderless_monocle true
bspc config gapless_monocle false
bspc config single_monocle true
bspc config click_to_focus any
bspc config pointer_follows_monitor true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

bspc config pointer_modifier mod4
bspc config pointer_action3 resize_side
bspc config pointer_action3 resize_corner
bspc config pointer_action1 moveasd

bspc rule -a \* node=focused
bspc rule -a xfce4-popup-whiskermenu state=floating border=off layer=normal
bspc rule -a Yad state=floating border=off layer=normal
bspc rule -a xfce4-notes floating=on

# Set wmname to LG3D to fix JAVA Window Problems
#wmname LG3D
